### ISSUE TITLE
Ignoring all commits

### ISSUE THREAD

**Issue by tobiastom** [stevemao/conventional-changelog-ember#3]
Maybe I'm wrong, and this is the intentional behavior, but doesn't the `!commit.pr` in https://github.com/conventional-changelog/conventional-changelog-ember/blob/master/index.js#L20 prevent this preset to work at all?

**Comment by stevemao** [comment]
ember is generating entries from PRs not the actual commits.

**Comment by tobiastom** [comment]
Ah, ok. I think that makes it not really broadly usable but I understand it.

Thanks for your fast response!
